# Generated by Django 5.2.8 on 2025-12-01 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('IVID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('BalanceDue', models.DecimalField(decimal_places=2, max_digits=15)),
                ('POno', models.CharField(max_length=50)),
                ('Quantity', models.IntegerField()),
                ('Description', models.TextField()),
                ('UnitPrice', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ReportID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='reports.report')),
            ],
        ),
    ]
