# Generated by Django 5.2.8 on 2025-12-01 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_expense', models.DecimalField(decimal_places=2, max_digits=15)),
                ('net_income', models.DecimalField(decimal_places=2, max_digits=15)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='income_statement', to='reports.report')),
            ],
        ),
    ]
