# Generated by Django 5.2.8 on 2025-12-01 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('PaymentID', models.AutoField(primary_key=True, serialize=False)),
                ('Currency', models.CharField(default='USD', max_length=10)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('CreditCardNo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('BankCredit', models.CharField(max_length=100)),
                ('NameCredit', models.CharField(max_length=100)),
                ('PaymentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_card', to='transactions.payment')),
            ],
        ),
        migrations.CreateModel(
            name='Cash',
            fields=[
                ('CashTransactionNo', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('NameCash', models.CharField(max_length=100)),
                ('CashTendered', models.DecimalField(decimal_places=2, max_digits=15)),
                ('PaymentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash', to='transactions.payment')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('TransactionID', models.AutoField(primary_key=True, serialize=False)),
                ('DateOfTransaction', models.DateTimeField(auto_now_add=True)),
                ('Description', models.TextField(blank=True)),
                ('BankName', models.CharField(max_length=100)),
                ('Debit', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('Credit', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('TotalAmount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('AccountID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='TransactionID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='transactions.transaction'),
        ),
    ]
