# Generated by Django 5.2.8 on 2025-12-01 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('ReportID', models.AutoField(primary_key=True, serialize=False)),
                ('DateRange', models.DateField()),
                ('Status', models.CharField(default='draft', max_length=50)),
                ('AccountID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
                ('TransactionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='transactions.transaction')),
            ],
        ),
    ]
